version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
      - ./db:/docker-entrypoint-initdb.d # 초기화 스크립트 mount
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_INITDB_DATABASE: mydb

  gateway:
    build:
      context: .
      dockerfile: apps/gateway-server/Dockerfile
    env_file:
      - ./.env
    container_name: gateway-server
    ports:
      - '3000:3000'
    volumes:
      - ./apps/common:/app/common
    depends_on:
      - auth
      - event
      - mongo

  auth:
    build:
      context: .
      dockerfile: apps/auth-server/Dockerfile
    container_name: auth-server
    env_file:
      - ./.env
    ports:
      - '3001:3001'
    volumes:
      - ./apps/common:/app/common
    depends_on:
      - mongo

  event:
    build:
      context: .
      dockerfile: apps/event-server/Dockerfile
    container_name: event-server
    env_file:
      - ./.env
    ports:
      - '3002:3002'
    volumes:
      - ./apps/common:/app/common
    depends_on:
      - mongo

volumes:
  mongo_data:
